cdef double cmse_Lq(double alpha, double tau, double M, double epsilon, double q, double tol=*)
cdef double cmse_Lq_dalpha(double alpha, double tau, double M, double epsilon, double q, double tol=*)
cdef double ctau_of_alpha(double alpha, double M, double q, double epsilon, double delta, double sigma, double tol=*)
cdef double coptimal_alpha(double M, double q, double epsilon, double delta, double sigma, double tol=*)
cdef double clambda_of_alpha_Lq(double alpha, double M, double epsilon, double delta, double sigma, double q, double tol)
cdef double calpha_of_lambda_Lq(double lam, double M, double epsilon, double delta, double sigma, double q, double tol)
